import { NodeData, Node, Bounds, Point, Size, IViewModel, IViewNode, ViewNodeChangeListener, ViewNodeChangeEvent, EdgeConnectorType, IEdge } from "./types";
export default class ViewNode implements IViewNode {
    joint?: boolean;
    editing?: boolean;
    dependencies?: string[];
    id: string;
    data?: NodeData;
    children?: Node[];
    parentId?: string;
    collapse?: boolean;
    x: number;
    y: number;
    width: number;
    height: number;
    listeners: ViewNodeChangeListener[];
    ref: HTMLElement;
    edgeConnectorType: EdgeConnectorType;
    readonly model: IViewModel;
    constructor(node: Node, joint: boolean, model: IViewModel, edgeConnectorType?: EdgeConnectorType);
    cloneWithProps(): IViewNode;
    resize(size: Size): void;
    addChildNode(node: Node, point: Point, joint?: boolean): Node;
    removeDependency(node: IViewNode): boolean;
    connect(node: IViewNode): IEdge;
    findConnected(runAfter?: boolean): Node[];
    findEdgesAsSource(): IEdge[];
    findEdgesAsTarget(): IEdge[];
    doLayout(): void;
    setPoint(point: Point, fireNodeChange?: boolean): void;
    setBounds(bounds: Bounds, fireChangeEvent?: boolean): void;
    shrink(): void;
    expand(): void;
    withChildren(promise: Promise<Node[]>, useCache?: boolean): void;
    refresh(): void;
    remove(): void;
    addNodeChangeListener: (listener: ViewNodeChangeListener) => void;
    removeNodeChangeListener: (listener: ViewNodeChangeListener) => void;
    fireNodeChange: (e: ViewNodeChangeEvent) => void;
    destory(): void;
}
